#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [ $(xrandr | grep "HDMI-0" | wc -l) -ge 1 ]; then
	bspc monitor eDP-1-1 -d I II III IV V VI VII
	bspc monitor HDMI-O -d VIII IX
else
	bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
fi

bspc config top_padding		 24
bspc config border_width         0
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^2' follow=off focus=off
bspc rule -a Anki desktop='^4'
bspc config ignore_ewmh_focus true

$HOME/.config/autostart.sh
$HOME/.config/polybar/launch.sh
